# Generated by Django 6.0.6 on 2026-07-10 11:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_alter_bookings_options_alter_bookings_event_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExpiredEvent',
            fields=[
            ],
            options={
                'verbose_name': 'Expired Event',
                'verbose_name_plural': 'Expired Events',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('home.bookings',),
        ),
    ]
