# Generated by Django 6.0.6 on 2026-07-10 11:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_expiredevent'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bookings',
            old_name='upadte_at',
            new_name='update_at',
        ),
    ]
